<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Categories extends MY_Controller {

    public $sess;

    function __construct() {
        parent::__construct();
        parent::_auth($this->uri->uri_string());
        $this->load->model('app/Categories_model');
        $this->load->model('app/Posts_model');
        $this->load->library('form_validation');
        $this->sess = $this->session->logged_in;
    }

    public function index() {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));

        if ($q <> '') {
            $config['base_url'] = base_url() . 'web/categories/index?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'web/categories/index?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'web/categories/index';
            $config['first_url'] = base_url() . 'web/categories/index';
        }

        $config['per_page'] = $this->config->item('site_limit_post');
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Posts_model->get_total_public_post_rows($q);
        $posts = $this->Posts_model->get_public_post($config['per_page'], $q, $start);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $recentpost = $this->Posts_model->get_public_post($this->config->item('site_limit_post'));
        $categorycount = $this->Categories_model->get_posts_count();

        $data = array(
            'posts' => $posts,
            'recentpost' => $recentpost,
            'categorycount' => $categorycount,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'template' => 'posts',
        );

        if (!empty($posts)) {
            $data = array(
                'posts' => $posts,
                'recentpost' => $recentpost,
                'categorycount' => $categorycount,
                'q' => $q,
                'pagination' => $this->pagination->create_links(),
                'total_rows' => $config['total_rows'],
                'start' => $start,
                'template' => 'posts',
            );
        } else {
            $data = array(
                'posts' => $posts,
                'recentpost' => $recentpost,
                'categorycount' => $categorycount,
                'q' => $q,
                'pagination' => $this->pagination->create_links(),
                'total_rows' => $config['total_rows'],
                'start' => $start,
                'template' => '404',
            );
        }
        $this->load->view('base/content', $data);
    }

}

/* End of file Categories.php */
/* Location: ./application/controllers/Categories.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-02-22 06:11:03 */
/* http://harviacode.com */