<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Comments_model extends CI_Model
{

    public $table = 'comments';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('c.*, p.title');
        $this->db->from('comments c');
        $this->db->join('posts p', 'p.id=c.postid', 'left');
        $this->db->where('c.id', $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->select('c.*, p.title');
        $this->db->from('comments c');
        $this->db->join('posts p', 'p.id=c.postid', 'left');
        $this->db->group_start();
        $this->db->like('c.id', $q);
        $this->db->or_like('c.postid', $q);
        $this->db->or_like('c.comment', $q);
        $this->db->or_like('c.authorname', $q);
        $this->db->or_like('c.authoremail', $q);
        $this->db->or_like('c.authorip', $q);
        $this->db->or_like('c.approved', $q);
        $this->db->or_like('c.createdat', $q);
        $this->db->or_like('c.createdby', $q);
        $this->db->or_like('c.updatedat', $q);
        $this->db->or_like('c.updatedby', $q);
        $this->db->group_end();
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->select('c.*, p.title');
        $this->db->from('comments c');
        $this->db->join('posts p', 'p.id=c.postid', 'left');
        $this->db->order_by('c.id', $this->order);
        $this->db->group_start();
        $this->db->like('c.id', $q);
        $this->db->or_like('c.postid', $q);
        $this->db->or_like('c.comment', $q);
        $this->db->or_like('c.authorname', $q);
        $this->db->or_like('c.authoremail', $q);
        $this->db->or_like('c.authorip', $q);
        $this->db->or_like('c.approved', $q);
        $this->db->or_like('c.createdat', $q);
        $this->db->or_like('c.createdby', $q);
        $this->db->or_like('c.updatedat', $q);
        $this->db->or_like('c.updatedby', $q);
        $this->db->group_end();
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Comments_model.php */
/* Location: ./application/models/Comments_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-02-22 06:11:03 */
/* http://harviacode.com */