<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pages_model extends CI_Model {

    public $table = 'posts';
    public $id = 'id';
    public $order = 'Desc';
    public $type = 'pages';

    function __construct() {
        parent::__construct();
    }

    // get all
    function get_all() {
        $this->db->where('type', $this->type);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id) {
        $this->db->where('type', $this->type);
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    //get data by slug
    function get_by_slug($slug) {
        $this->db->where('type', $this->type);
        $this->db->where('slug', $slug);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->where('type', $this->type);
        $this->db->group_start();
        $this->db->like('id', $q);
        $this->db->or_like('guuid', $q);
        $this->db->or_like('title', $q);
        $this->db->or_like('categoryid', $q);
        $this->db->or_like('content', $q);
        $this->db->or_like('postimage', $q);
        $this->db->or_like('type', $q);
        $this->db->or_like('metapost', $q);
        $this->db->or_like('keywords', $q); //        $this->db->or_like('commentstatus', $q);
        $this->db->or_like('poststatus', $q);
        $this->db->or_like('createdat', $q);
        $this->db->or_like('createdby', $q);
        $this->db->or_like('updatedat', $q);
        $this->db->or_like('updatedby', $q);
        $this->db->group_end();
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->where('type', $this->type);
        $this->db->order_by($this->id, $this->order);
        $this->db->group_start();
        $this->db->like('id', $q);
        $this->db->or_like('guuid', $q);
        $this->db->or_like('title', $q);
        $this->db->or_like('categoryid', $q);
        $this->db->or_like('content', $q);
        $this->db->or_like('postimage', $q);
        $this->db->or_like('type', $q);
        $this->db->or_like('metapost', $q);
        $this->db->or_like('keywords', $q); //        $this->db->or_like('commentstatus', $q);
        $this->db->or_like('poststatus', $q);
        $this->db->or_like('createdat', $q);
        $this->db->or_like('createdby', $q);
        $this->db->or_like('updatedat', $q);
        $this->db->or_like('updatedby', $q);
        $this->db->group_end();
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->where('type', $this->type);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->where('type', $this->type);
        $this->db->delete($this->table);
    }

}

/* End of file Posts_model.php */
/* Location: ./application/models/Posts_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-21 12:45:37 */
/* http://harviacode.com */