<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Classes extends MY_Controller {
    public $sess;
    function __construct() {
        parent::__construct();
        parent::_auth($this->uri->uri_string());
        $this->load->model('Classes_model');
        $this->load->library('form_validation');
        $this->sess = $this->session->logged_in;
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'app/classes/index?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'app/classes/index?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'app/classes/index';
            $config['first_url'] = base_url() . 'app/classes/index';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Classes_model->total_rows($q);
        $classes = $this->Classes_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'classes_data' => $classes,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'template' => 'classes/classes_list',
            'session' => $this->sess,
        );
        $this->load->view('base/content', $data);
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('app/classes/create_action'),
	    'id' => set_value('id'),
	    'classname' => set_value('classname'),
	    'template' => 'classes/classes_form',
            'session' => $this->sess,
        );
        $this->load->view('base/content', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'classname' => $this->input->post('classname',TRUE),
        'createdat' => date("Y-m-d H:i:s"),
        'createdby' => $this->sess['id'],
        'updatedat' => date("Y-m-d H:i:s"),
        'updatedby' => $this->sess['id'],
	    );

            $this->Classes_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('app/classes'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Classes_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('app/classes/update_action'),
		'id' => set_value('id', $row->id),
		'classname' => set_value('classname', $row->classname),
		'template' => 'classes/classes_form',
            'session' => $this->sess,
        );
        $this->load->view('base/content', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('app/classes'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'classname' => $this->input->post('classname',TRUE),
        'updatedat' => date("Y-m-d H:i:s"),
        'updatedby' => $this->sess['id'],
	    );

            $this->Classes_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('app/classes'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Classes_model->get_by_id($id);

        if ($row) {
            $this->Classes_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('app/classes'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('app/classes'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('classname', 'classname', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Classes.php */
/* Location: ./application/controllers/Classes.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-02-22 06:11:03 */
/* http://harviacode.com */