<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Comments extends MY_Controller
{
    public $sess;
    function __construct()
    {
        parent::__construct();
        parent::_auth($this->uri->uri_string());
        $this->load->model('Comments_model');
        $this->load->library('form_validation');
        $this->sess = $this->session->logged_in;
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'app/comments/index?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'app/comments/index?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'app/comments/index';
            $config['first_url'] = base_url() . 'app/comments/index';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Comments_model->total_rows($q);
        $comments = $this->Comments_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'comments_data' => $comments,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'template' => 'comments/comments_list',
            'session' => $this->sess,
        );
        $this->load->view('base/content', $data);
    }

    public function read($id) 
    {
        $row = $this->Comments_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'post' => $row->title,
		'comment' => $row->comment,
		'authorname' => $row->authorname,
		'authoremail' => $row->authoremail,
		'authorip' => $row->authorip,
		'approved' => $row->approved,
		'createdat' => $row->createdat,
		'createdby' => $row->createdby,
		'updatedat' => $row->updatedat,
		'updatedby' => $row->updatedby,
	    'template' => 'comments/comments_read',
                'session' => $this->sess,
            );
            $this->load->view('base/content', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('app/comments'));
        }
    }

    
    public function update_action($commentid,$status) 
    {
            $data = array(
		        'approved' => $status,   
                'updatedat' => date("Y-m-d H:i:s"),
                'updatedby' => $this->sess['id'],
	            );

            $this->Comments_model->update($commentid, $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('app/comments'));
    }
    
    public function delete($id) 
    {
        $row = $this->Comments_model->get_by_id($id);

        if ($row) {
            $this->Comments_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('app/comments'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('app/comments'));
        }
    }

}

/* End of file Comments.php */
/* Location: ./application/controllers/Comments.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-02-22 06:11:03 */
/* http://harviacode.com */