<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Media extends MY_Controller {

    public $sess;

    function __construct() {
        parent::__construct();
        parent::_auth($this->uri->uri_string());
        $this->load->model('Media_model');
        $this->load->library('form_validation');
        $this->sess = $this->session->logged_in;
    }

    public function index() {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));

        if ($q <> '') {
            $config['base_url'] = base_url() . 'app/media/index?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'app/media/index?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'app/media/index';
            $config['first_url'] = base_url() . 'app/media/index';
        }

        $config['per_page'] = 12;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Media_model->total_rows($q);
        $media = $this->Media_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'media_data' => $media,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'session' => $this->sess,
            'template' => 'media/media_list',
            'extracss' => 'media/media_css_list',
            'extrajs' => 'media/media_js_list',
        );
        $this->load->view('base/content', $data);
    }

    public function create() {
        $data = array(
            'button' => 'Create',
            'action' => site_url('app/media/create_action'),
            'template' => 'media/media_form',
            'extracss' => 'media/media_css_upload',
            'extrajs' => 'media/media_js_upload',
            'session' => $this->sess,
        );
        $this->load->view('base/content', $data);
    }

    public function create_action() {
        if (!empty($_FILES['file'])) {
            $result = fileuploader($_FILES, "file", "", "gif|jpeg|jpg|png|pdf|doc|docx|xlsx|xls|ppt|pptx|zip|rar");
            if ($result['status'] == "success") {
                $data = array(
                    'filename' => $result['message']['filename'],
                    'filepath' => $result['message']['filepath'],
                    'fullpath' => $result['message']['fullpath'],
                    'filetype' => $result['message']['filetype'],
                    'createdat' => date("Y-m-d H:i:s"),
                    'createdby' => $this->sess['id'],
                    'updatedat' => date("Y-m-d H:i:s"),
                    'updatedby' => $this->sess['id'],
                );
                $this->Media_model->insert($data);
                echo $this->security->get_csrf_hash();
            } else {
                $this->session->set_flashdata('foto-error', $result['message']);
            }
        }
    }

    public function delete($id) {
        $row = $this->Media_model->get_by_id($id);

        if ($row) {
            $this->Media_model->delete($id);
            unlink($row->fullpath);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('app/media'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('app/media'));
        }
    }

    public function _rules() {
        $this->form_validation->set_rules('file', 'file', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Media.php */
/* Location: ./application/controllers/Media.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-18 05:28:32 */
/* http://harviacode.com */