<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Settings extends MY_Controller {

    public $sess;

    function __construct() {
        parent::__construct();
        parent::_auth($this->uri->uri_string());
        $this->load->model('Settings_model');
        $this->load->library('form_validation');
        $this->sess = $this->session->logged_in;
    }

    public function index() {
        $settings = $this->Settings_model->get_all();
        $data = array(
            'button' => 'Update',
            'action' => site_url('app/settings/update_action'),
            'template' => 'settings/settings_form',
            'session' => $this->sess,
        );
        foreach ($settings as $key) {
            $data[$key->setting_name] = $key->setting_value;
        }
        $this->load->view('base/content', $data);
    }

    public function update_action() {
        $sttg = $this->input->post();

        $sttg['smtp_pass'] = base64_encode($sttg['smtp_pass']);
        foreach ($sttg as $key => $val) {
            $this->Settings_model->update($key, array('setting_value' => $val));
        }

        if (!empty($_FILES['filelogo']['name'])) {
            $result = fileuploader($_FILES, "filelogo");
            $this->Settings_model->update("site_logo", array('setting_value' => $result['message']['fullpath']));
        }

        if (!empty($_FILES['fileicon']['name'])) {
            $result = fileuploader($_FILES, "fileicon");
            $this->Settings_model->update("site_icon", array('setting_value' => $result['message']['fullpath']));
        }

        if (!empty($_FILES['filesitehomebg']['name'])) {
            $result = fileuploader($_FILES, "filesitehomebg");
            $this->Settings_model->update("site_home_bg", array('setting_value' => $result['message']['fullpath']));
        }
        if (!empty($_FILES['filesitewebbg']['name'])) {
            $result = fileuploader($_FILES, "filesitewebbg");
            $this->Settings_model->update("site_web_bg", array('setting_value' => $result['message']['fullpath']));
        }

        redirect(site_url('app/settings'));
    }

    public function delete($id) {
        $row = $this->Settings_model->get_by_id($id);

        if ($row) {
            $this->Settings_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('app/settings'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('app/settings'));
        }
    }

}

/* End of file Settings.php */
/* Location: ./application/controllers/Settings.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-17 14:03:47 */
/* http://harviacode.com */